import Head from "next/head";

import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Smartfony from "../components/SmartfonyPage";
import AccessoriesPage from "../components/AccessoriesPage";
import ServicePage from "../components/ServicePage";
import AboutMePage from "../components/AboutMePage";
import GeneralInfo from "../components/GeneralInfo";
import FAQPage from "../components/FAQPage";
import DPD from "../components/DPD";
import ContactPage from "../components/ContactPage";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <Smartfony />
      <AccessoriesPage />
      <ServicePage />
      <AboutMePage />
      <GeneralInfo />
      <FAQPage />
      <DPD />
      <ContactPage />
      <Footer />
    </div>
  );
}
